## Opgave

Laad de volgende dataset in: heart.csv - deze dataset bevat informatie over patiënten met hartproblemen. 

Pas op deze dataset minstens 2 goede classificatiemethodes toe. Zorg voor preprocessing waar nodig, en zoek naar een optimaal model. **Indien je bepaalde keuzes maakt, schrijf kort in de notebook waarom**.

### Inleveren:
- Hernoem je bestand naar **PE1-VoornaamNaam.ipynb** waarbij je je *eigen naam* invult.
- Laadt dit bestand op naar de uploadzone op toets.ap.be voor het einde van deze test.

Jullie krijgen **60 minuten** de tijd. Bedenk dus dat als de dataset groot is, training lang kan duren. Perfectioneer eerst je model op een kleinere dataset.

### Indicatieve puntenverdeling /20
- goede algoritmes: 2 keer 4 ptn
- goede beschrijving over keuze van deze algoritmes: 4 ptn
- overige noodzakelijke stappen: 8 ptn
- Hierna wordt er gekeken naar code stijl

### Meer info over de features van deze dataset:

- age   Age of the patient in years
- sex 	Gender of the patient (0 = male, 1 = female)
- cp 	Chest pain type:
    - 0: Typical angina
    - 1: Atypical angina
    - 2: Non-anginal pain
    - 3: Asymptomatic
- trestbps 	Resting blood pressure in mm Hg
- chol 	Serum cholesterol in mg/dl
- fbs 	Fasting blood sugar level, categorized as above 120 mg/dl (1 = true, 0 = false)
- restecg 	Resting electrocardiographic results:
    - 0: Normal
    - 1: Having ST-T wave abnormality
    - 2: Showing probable or definite left ventricular hypertrophy
- thalach 	Maximum heart rate achieved during a stress test
- exang 	Exercise-induced angina (1 = yes, 0 = no)
- oldpeak 	ST depression induced by exercise relative to rest
- slope 	Slope of the peak exercise ST segment:
    - 0: Upsloping
    - 1: Flat
    - 2: Downsloping
- ca 	Number of major vessels (0-4) colored by fluoroscopy
- thal 	Thalium stress test result:
    - 0: Normal
    - 1: Fixed defect
    - 2: Reversible defect
    - 3: Not described
- **target** 	Heart disease status (0 = no disease, 1 = presence of disease)

In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, classification_report, confusion_matrix

In [54]:
df = pd.read_csv('./data/heart.csv')
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [55]:
print(df.dtypes)
print(df.isna().sum())

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [56]:
X, y = df.drop(columns=['target']), df['target']

In [57]:
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [58]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
scaler = StandardScaler()

categorical_features = ['sex', 'fbs', 'exang']
continious_features = [c for c in X.columns if c not in categorical_features]

continious_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

preprocessor = ColumnTransformer(
    transformers=[
        ('continious', continious_transformer, continious_features),
        ('cat', 'passthrough', categorical_features)
    ]
)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', SVC(kernel='linear', random_state=42))
])
pipe.fit(X_train, y_train)
preds = pipe.predict(X_test)

accuracy = accuracy_score(y_test, preds)
conf_matrix = confusion_matrix(y_test, preds)
class_report = classification_report(y_test, preds)
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

Accuracy: 0.81
Confusion Matrix:
[[32  9]
 [ 8 42]]
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.78      0.79        41
           1       0.82      0.84      0.83        50

    accuracy                           0.81        91
   macro avg       0.81      0.81      0.81        91
weighted avg       0.81      0.81      0.81        91

In [59]:
svc = SVC(kernel='linear', random_state=42)
parameters = {'svc__kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'svc__C': [1, 5, 10]}

pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('svc', svc)
])

grid = GridSearchCV(pipe, parameters, cv=5)

grid.fit(X_train, y_train)
preds = grid.predict(X_test)

accuracy = accuracy_score(y_test, preds)
conf_matrix = confusion_matrix(y_test, preds)
class_report = classification_report(y_test, preds)
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)
print(grid.best_params_)

Accuracy: 0.80
Confusion Matrix:
[[32  9]
 [ 9 41]]
Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.78      0.78        41
           1       0.82      0.82      0.82        50

    accuracy                           0.80        91
   macro avg       0.80      0.80      0.80        91
weighted avg       0.80      0.80      0.80        91

{'svc__C': 1, 'svc__kernel': 'rbf'}

In [61]:
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

knn_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('knn', KNeighborsClassifier(n_neighbors=5))
])

xgb = Pipeline([
    ('preprocessor', preprocessor),
    ('xgb', XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42))
])

voting = VotingClassifier(estimators=[
    ('svc', grid), ('knn', knn_pipe), ('xgb', xgb)
], voting='hard')
voting.fit(X_train, y_train)
preds = voting.predict(X_test)

accuracy = accuracy_score(y_test, preds)
conf_matrix = confusion_matrix(y_test, preds)
class_report = classification_report(y_test, preds)
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)
print(voting.estimators)

Accuracy: 0.81
Confusion Matrix:
[[32  9]
 [ 8 42]]
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.78      0.79        41
           1       0.82      0.84      0.83        50

    accuracy                           0.81        91
   macro avg       0.81      0.81      0.81        91
weighted avg       0.81      0.81      0.81        91

[('svc', GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('continious',
                                                                         Pipeline(steps=[('scaler',
                                                                                          StandardScaler())]),
                                                                         ['age',
                                                                          'cp',
                                                                          'trestbps',
                                                                          'chol',
                                                                          'restecg',
                                                                          'thalach',
                                                                          'oldpeak',
                                                                          'slope',
                                                                          'ca',
                                                                          'thal']),
                                                                        ('cat',
                                                                         'passthrough',
                                                                         ['sex',
                                                                          'fbs',
                                                                          'exang'])])),
                                       ('svc',
                                        SVC(kernel='linear',
                                            random_state=42))]),
             param_grid={'svc__C': [1, 5, 10],
                         'svc__kernel': ['linear', 'poly', 'rbf', 'sigmoid']})), ('knn', Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('continious',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'cp', 'trestbps',
                                                   'chol', 'restecg', 'thalach',
                                                   'oldpeak', 'slope', 'ca',
                                                   'thal']),
                                                 ('cat', 'passthrough',
                                                  ['sex', 'fbs', 'exang'])])),
                ('knn', KNeighborsClassifier())])), ('xgb', Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('continious',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'cp', 'trestbps',
                                                   'chol', 'restecg', 'thalach',
                                                   'oldpeak', 'slope', 'ca',
                                                   'thal']),
                                                 ('cat', 'passthrough',
                                                  ['sex', 'fbs', 'exang'])])),
                ('xgb',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample...
                               feature_types=None, gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=3, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=100, n_jobs=None,
                               num_parallel_tree=None, random_state=42, ...))]))]